{
 "title": "Greenatom",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Missions and rockets that did it",
   "type": "table",
   "gridPos": { "h": 14, "w": 21, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT missions.name as mission_name, rockets.name as rocket_name, rockets.type rocket_type, rockets.country rocket_country, rockets.cost_per_launch FROM launches JOIN missions ON missions.id = mission_id JOIN rockets ON rocket_id=rockets.id;"
    }
   ]
  },
  {
   "title": "Number of launches",
   "type": "stat",
   "gridPos": { "h": 14, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(mission_id) as quantity FROM launches;"
    }
   ]
  },
  {
   "title": "Falcon 1 quantity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(rocket_id) from launches WHERE rocket_id=1;"
    }
   ]
  },
  {
   "title": "Falcon 9 quantity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(rocket_id) from launches WHERE rocket_id=2;"
    }
   ]
  },
  {
   "title": "Falcon Heavy quantity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(rocket_id) from launches WHERE rocket_id=3;"
    }
   ]
  }
 ]
}