CREATE TABLE IF NOT EXISTS missions(
    ID TEXT PRIMARY KEY,
    Name TEXT
);
CREATE TABLE IF NOT EXISTS rockets(
    ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    Name TEXT,
    Type TEXT,
    Country TEXT,
    Cost_per_launch INTEGER
);
CREATE TABLE IF NOT EXISTS launches(
    ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    Rocket_ID INTEGER REFERENCES rockets ON DELETE CASCADE,
    Mission_ID TEXT REFERENCES missions ON DELETE CASCADE
);
